### DISCUSSION TITLE
Custom styles for AxelChat widgets (Custom CSS)

### DISCUSSION THREAD

**Discussion by 3dproger** [3dproger/AxelChat#621] [Info]
Here you can find Custom CSS styles for AxelChat widgets and you can also share your styles with the user community. Instructions for installing styles can be found here: https://github.com/3dproger/AxelChat/discussions/622

When publishing your CSS style, please follow these instructions:
<details>
<summary>Click this to expand</summary>

When publishing your CSS style, please include the following information:

1. Title of widget
1. Description - Here, please describe the features of your style if necessary
1. Widgets - The names of the widgets this style is intended for. You can specify several if necessary
1. Author - The name of the author of the style. If you are the author, then it is not necessary to indicate this
1. Latest tested version of AxelChat - The version of AxelChat that your style is compatible with. Here it is enough to specify the latest version with which you tested your style
1. Preview - A screenshot or gif previewing your style. You can add several if needed
1. CSS - CSS code of your style
1. You can also add any other information at your discretion. Preferably, in the comments to your post

To make it easier look at examples of those who have done it before you

</details>

**Comment by 3dproger** [comment]
# Restream like chat

It's meant to mimic Restream Chat, as such it runs top to bottom, and has a slide in animation with a little bounce. among other changes. Also I only use youtube and twitch chats here.

* Author: @SpacemannFinn
* Widgets: Messages, Selected Messages
* Latest tested version of AxelChat: 0.38.7-beta

Preview:

![messages-cover](https://github.com/user-attachments/assets/1cbde576-2615-4c13-aacd-d0f9b7defdc8)

CSS:
<details>
<summary>Click this to expand</summary>

```CSS
/*New Fonts*/
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');


#root > span > img[src='./images/tick.svg'], #root > span > img[src='./images/error-alt-svgrepo-com.svg']{
  display: none;
}

#root > span > .authorName {
  display: none;
}

#root .ant-spin.ant-spin-spinning,
#root .anticon.anticon-loading.anticon-spin {
  display: none;
}

/*-------------------------Animation--------------------------------------*/
.messagesListView > div:nth-last-child(2){
  position: relative;
  animation-name: slideIn;
  animation-duration: 0.3s;
  animation-iteration-count: 1;
  transition-timing-function: cubic-bezier(.75,-0.5,0,1.75);
}


@-webkit-keyframes slideIn{
  0%   {transform: translateX(100%)}
  80%  {transform: translateX(-2%)}
  90%  {transform:translateX(2%)}
  100% {transform: translateX(0%)}
}
/*------------------------------------------------------------*/


/*Moves username onto new line*/
span.authorName::after{
content: "\A";
  white-space: pre;
line-height:2;
vertical-align:top
}

/*Reverses the message order*/
.messagesListView{
  display:flex;
  flex-direction: column-reverse
}


/*---------------------------------message styling---------------------------*/
.message{
background: #253858;
  padding: 1rem;
  margin: 0.2rem 0;
  width: 400px;
  box-shadow: 5px 5px 5px rgba(37,56,88,0.4);
  border-radius: 0px;
}

.badgeServiceIcon {
  width: 12px;
  padding-right: 6px;
}

.badgeLeft, .badgeRight {
  display: none;
}


/*This removes the colon I believe?*/
span.text:nth-of-type(3) {
  display: none;
}


/*Pushes the actual message text downwards a little*/
.message :nth-child(n+4) {
  margin-top: 6px;
  word-wrap: anywhere;
}

/*------------------------------------------------------------*/


/*Transparent BG and removing scroll wheel*/
body{
  background-color: rgba(0,0,0,0);
overflow-y:hidden;
overflow-x:hidden;
}

/*--------------Finally using the fonts to change the name and messages to look nicer-------------------------*/
.authorName {
color: #D3D3D3 !important;
  font-family: "Poppins", sans-serif;
  font-style: normal;
  font-weight: 300;
font-size: 1rem;
} 

.authorMessageContentSeparator{
display: none
}

.text{
color: #FFF !important;
  font-family: "Inter", sans-serif;
font-size: 1.3rem;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
margin-top: 5px
}
```

</details>

**Reply by Aeon1704** [reply]
I've tried to disable the Null_Message with custom CSS - One which says "Connected!" with icon. Didn't work, maybe doing something wrong. What exactly is the element of that message? .null_message doesn't work.

**Reply by SpacemannFinn** [reply]
Here's some CSS for those issues I think @Aeon1704 

```
#root > span > img[src='./images/tick.svg'], #root > span > img[src='./images/error-alt-svgrepo-com.svg']{
  display: none;
}
```

This removes the tick and error images that show up before messages are sent

```
#root .ant-spin.ant-spin-spinning,
#root .anticon.anticon-loading.anticon-spin {
  display: none;
}

```

This removes the loading stuff too

I think this is what I use to remove everything. Idk if the connected text goes away but that can always be dealt with by hiding the chat till the first message pops in.

**Reply by Aeon1704** [reply]
Thank you, it does remove the icons, but message connected stays. But easy way will be to removes it from JS and leave it blank :D

**Reply by 3dproger** [reply]
Hi! I will try to make it possible to disable the display of such a message through the settings

**Reply by mtleont** [reply]
There is an option in the settings to remove the connected message.
<img width="442" height="53" alt="image" src="https://github.com/user-attachments/assets/4d3d4343-a011-4700-861f-b8742d59f0c3" />

**Comment by Aeon1704** [comment]
Simple Style I've made for myself.
-Widgets: Messages.
-Latest tested version of AxelChat: 0.38.7-beta.

Changes made to original style:
-New messages appear at bottom or top, moving old ones to top or bottom respectively. 
-Black-Transparent Background for messages.
-Grey-Transparent Border for messages.
-Blurred outline to all text.
-Disabled moderator badge and twitch-reward badge, only platform badge left.
-Minor changes to emote size, text size and spacing.
-Optional: Messages disappear after 30seconds. fade out animation.
-Optional: Alpha-Mask .png to use in OBS Filter to add fade away effect for bottom or top edge.
(Download .png and apply to Alpha-Mask filter in OBS for your AxelChat source from section below)
<details><summary>Alpha-mask .png</summary>

![Gradient2](https://github.com/user-attachments/assets/c2c27436-9335-40be-8a80-f9f114320696)
![Gradient2bottom](https://github.com/user-attachments/assets/3c1048dc-1197-493b-ae66-6a9e3007398a)

</details>

![изображение](https://github.com/user-attachments/assets/3002d08f-41ec-495f-a933-29785847b2b3)

<details><summary>CSS: New Messages at Bottom:</summary>

```
body {
background-color: rgba(0, 0, 0, 0);
overflow: clip;
width: 100%;
position: fixed;
bottom: 1px; 
margin: 0px auto;
}

.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85) !important;
width: 100%;
background-color: rgba(0, 0, 0, 0.65) !important;
}

.imageContent{height:22px;}
.authorMessageContentSeparator{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.text{
word-break: break-word;
letter-spacing: 1.5px;
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.authorName{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
}

.messagesListView{
  display:flex;
  flex-direction: column;
}

.badgeLeft, .badgeRight {
  display: none;
}
```

</details>

<details><summary>CSS: New Messages at Top:</summary>

```
body {
background-color: rgba(0, 0, 0, 0);
overflow: clip;
width: 100%;
bottom: 1px; 
margin: 0px auto;
}

.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85) !important;
width: 100%;
background-color: rgba(0, 0, 0, 0.65) !important;
}

.imageContent{height:22px;}
.authorMessageContentSeparator{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.text{
word-break: break-word;
letter-spacing: 1.5px;
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.authorName{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
}

.messagesListView{
width: 100%;
position: fixed;
top: 0;
  display:flex;
  flex-direction: column-reverse;
}

.badgeLeft, .badgeRight {
  display: none;
}
```
</details>

<details><summary>CSS: New Messages at Bottom, 30sec timer:</summary>

```
body {
background-color: rgba(0, 0, 0, 0);
overflow: clip;
width: 100%;
position: fixed;
bottom: 1px; 
margin: 0px auto;
}

.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85) !important;
animation: cssAnimation 30s forwards;
width: 100%;
background-color: rgba(0, 0, 0, 0.65) !important;
}
@keyframes cssAnimation {
    97%  {opacity: 1;}
    100% {opacity: 0;display:none}
}

.imageContent{height:22px;}
.authorMessageContentSeparator{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.text{
word-break: break-word;
letter-spacing: 1.5px;
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.authorName{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
}

.messagesListView{
  display:flex;
  flex-direction: column;
}

.badgeLeft, .badgeRight {
  display: none;
}
```

</details>

<details><summary>CSS: New Messages at Top, 30sec timer:</summary>

```
body {
background-color: rgba(0, 0, 0, 0);
overflow: clip;
width: 100%;
bottom: 1px; 
margin: 0px auto;
}

.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85) !important;
animation: cssAnimation 30s forwards;
width: 100%;
background-color: rgba(0, 0, 0, 0.65) !important;
}
@keyframes cssAnimation {
    97%  {opacity: 1;}
    100% {opacity: 0;display:none}
}
.imageContent{height:22px;}
.authorMessageContentSeparator{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.text{
word-break: break-word;
letter-spacing: 1.5px;
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
font-weight:400;
}

.authorName{
text-shadow:
-2px -2px 3px #000000,  
2px -2px 3px #000000,
-2px 2px 3px #000000,
2px 2px 3px #000000;
}

.messagesListView{
width: 100%;
position: fixed;
top: 0;
  display:flex;
  flex-direction: column-reverse;
}

.badgeLeft, .badgeRight {
  display: none;
}
```

</details>

**Reply by SpacemannFinn** [reply]
Love the styling and use of an Alpha Mask on this. Wish we could use some custom JS in OBS so I could make certain elements have animations that are user context specific

**Reply by Aeon1704** [reply]
I am not very good at advance CSS stuff, one thing i want to add for my style is Timestamp. I can see in JS - function(e){return e.timeStamp||Date.now()} - which i guess is the data for it. Is there a way to put that data from JS into CSS variable?

**Reply by 3dproger** [reply]
> I am not very good at advance CSS stuff, one thing i want to add for my style is Timestamp. I can see in JS - function(e){return e.timeStamp||Date.now()} - which i guess is the data for it. Is there a way to put that data from JS into CSS variable?

The style looks great!

To display the message time, I will try to add this option to enable through the settings

**Reply by 3dproger** [reply]
> Love the styling and use of an Alpha Mask on this. Wish we could use some custom JS in OBS so I could make certain elements have animations that are user context specific

It would be great to integrate your own JS into OBS just like CSS, but apparently it is not supported. Maybe you can come up with some other way. Of course, you can also fork this repository and edit the code if you have experience in this. This way you will get your own version of the widget, which you can customize as you wish. I will also publish this widget for all users

**Reply by Aeon1704** [reply]
> To display the message time, I will try to add this option to enable through the settings

That will be cool :)

**Reply by spikehidden** [reply]
Just noticed that using "New Messages at Top" style, it scrolls in the wrong direction when recieving a new message. It scrolls down on every new message, showing old messages instead of the newest one.

**Reply by Aeon1704** [reply]
Thats odd, because i did test it alot, atleast in older version of AxelChat. Worked alright.
Kinda weird because 
```
.messagesListView{
width: 100%;
  display:inline-flex;
  flex-direction: column-reverse;
}
```
fixes it. Java code doesn't seem to like "display:flex;" method, maybe :D I will see to it later, will try to find other solutions.

**Reply by Aeon1704** [reply]
I did modify the "On top" variation with more stable solution. 
```
.messagesListView{
width: 100%;
position: fixed;
top: 0;
  display:flex;
  flex-direction: column-reverse;
}
```
Full CSS code updated in top message too.
Messages should appear on Top, and scroll down the new ones to bottom edge and beyond.
<img width="613" height="648" alt="изображение" src="https://github.com/user-attachments/assets/90e917d9-f260-4a8f-abe9-0827f6924618" />

**Reply by spikehidden** [reply]
Thanks a lot!
❤️🦊

**Reply by hlustinaleksandr-cpu** [reply]
как сделать его прозрачным?

**Reply by Aeon1704** [reply]
> как сделать его прозрачным?

Если хотите убрать фон именно с моего стиля есть секция CSS кода:
```
.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85);
width: 100%;
background-color: rgba(0, 0, 0, 0.65);
}
```
Удалите строки:
```
background-color: rgba(0, 0, 0, 0.65);
border-color: rgba(35, 35, 35, 0.85);
```
или замените их на:
```
background-color: rgba(0, 0, 0, 1);
border-color: rgba(0, 0, 0, 1);
```

**Reply by arkdiz-hub** [reply]
> Если вы хотите убрать фон именно с моего стиля, есть секция CSS-кода:

а у меня наоборот, почему-то фон прозрачный, а не как у вас на скрине, в самом коде я ничего не меняла

**Reply by Aeon1704** [reply]
Скорее всего у вас включена настройка фона в самом приложении. Ее нужно отключить. Либо модифицировать строку до:
```
background-color: rgba(0, 0, 0, 0.65) !important;
border-color: rgba(0, 0, 0, 0.85) !important;
```

**Reply by arkdiz-hub** [reply]
> !important;

в приложении отключено
и чат выглядит вот так
<img width="543" height="171" alt="Снимок экрана 2026-01-26 034536" src="https://github.com/user-attachments/assets/414651b3-704d-4bd4-b970-6811a6d1b262" />

**Reply by Aeon1704** [reply]
Видимо версия обновилась и теперь там жесткие настройки для фона сообщений.
Заменил настройки стиля:
```
.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85);
width: 100%;
background-color: rgba(0, 0, 0, 0.65);
}
```

на

```
.message{
padding: 1px;
vertical-align: baseline;
border-radius: 10px;
border-style: solid;
border-color: rgba(35, 35, 35, 0.85) !important;
width: 100%;
background-color: rgba(0, 0, 0, 0.65) !important;
}
```
Custom CSS должен игнорировать настройки фона приложения. Попробуйте скопировать любой из предложенных кодов в первом посте.

**Reply by arkdiz-hub** [reply]
> .message{
> padding: 1px;
> vertical-align: baseline;
> border-radius: 10px;
> border-style: solid;
> border-color: rgba(35, 35, 35, 0.85) !important;
> width: 100%;
> background-color: rgba(0, 0, 0, 0.65) !important;
> }

помогло, спасибо

**Comment by hlustinaleksandr-cpu** [comment]
А как поставить мне такой стиль, подскажите пожалуйста!

**Reply by toffeehpa** [reply]
какой именно?

**Reply by Aeon1704** [reply]
Когда вы добавите виджет AxelChat в свой обс, кликните правой кнопкой - свойства. Будет поле CSS. Скопируйте туда код CSS, предложенный выше.

**Comment by viiiksw** [comment]
is it possible to limit the words in a line? I want to make the chat not so long horizontally, and I would like to be able to adjust the line break. can someone help with this, please?

**Reply by Aeon1704** [reply]
Not sure exactly, horizontal limit is set in your Scene Element. But if you want message to appear in one line and simply being, let's say, cut. You can try to add this.
    _.message{
height: (set the number, remove brackets)px;
overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
}_

You need to adjust the "height" property and set proper size(number) to it, matching your font size. Otherwise it will not work, but it will cut too big text and will place it in single line
<img width="871" height="65" alt="изображение" src="https://github.com/user-attachments/assets/fabd8b4e-16a0-4330-971a-dc8964c2142b" />
<img width="523" height="64" alt="изображение" src="https://github.com/user-attachments/assets/bd239b7d-8c28-44ce-aa49-056c82c29043" />

**Comment by zigarot** [comment]
## Zig's Bubbles.
Description - Separate out the Sender and Message into two different fields. Thought I'd apply my meager knowledge of css and some sleuthing to uncover some fields I couldn't find.
Widgets - Messages / Highlights
Latest tested version of AxelChat - 0.47.2

You can edit the root fields to customise background colours, font sizes, and bevel (radius). Advanced changes, you'll need to get in the nitty gritty.
<img width="589" height="370" alt="image" src="https://github.com/user-attachments/assets/89893349-ba99-4b00-9732-3da732c0b74d" />

CSS:
<details>
  <summary>Highlights (right aligned)</summary>
Works well with 800x600 window to show off top comments

``` css
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=DM+Sans:opsz,wght@9..40,300;9..40,400&display=swap');

:root {
  --sender-bg: rgba(177, 162, 202, 0.85);
  --sender-radius: 4vw 4vw 0 4vw;
  --sender-height: 6vw;
  --message-bg: rgba(37, 58, 35, 0.85);
  --message-radius: 4vw 0 4vw 4vw;
  --message-fontsize: 6vw;
}

body {
  background: transparent;
  overflow: hidden;
  display: flex;
  align-items: flex-end;
  justify-content: flex-end;
  padding: 2vw;
  box-sizing: border-box;
  margin: 0;
}

#root > span > img[src='./images/tick.svg'],
#root > span > img[src='./images/error-alt-svgrepo-com.svg'],
#root .ant-spin.ant-spin-spinning,
#root .anticon.anticon-loading.anticon-spin {
  display: none;
}

.messagesListView {
  display: flex;
  flex-direction: column;
  gap: 2vw;
  width: 100%;
}

.message {
  display: flex !important;
  flex-direction: column;
  align-items: flex-end;
  background: transparent !important;
  border: none !important;
  padding: 0 !important;
  width: 100%;
  gap: 0.5vw;
  animation: spotIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) both;
}

@keyframes spotIn {
  from { opacity: 0; transform: scale(0.9) translateY(14px); }
  to   { opacity: 1; transform: scale(1)   translateY(0px); }
}

.author {
  display: inline-flex !important;
  align-items: center;
  height: var(--sender-height);
  padding: 1.2vw 0.6vw 1.2vw 1.8vw;
  background: var(--sender-bg) !important;
  border-radius: var(--sender-radius);
  box-sizing: content-box;
}

/* author sub-items */
.badgeServiceIcon,
.avatar,
.badgeLeft,
.badgeRight {
  display: inline-flex !important;
  align-items: center;
  height: var(--sender-height);
  width: auto;
  box-sizing: content-box;
  border-radius: 20%;
}

.avatar {
  object-fit: cover;
  overflow: hidden;
}

.badgeLeft,
.badgeRight {
  gap: 0.5vw;
}

.badgeLeft .imageContent,
.badgeRight .imageContent {
  height: var(--sender-height) !important;
  width: auto;
}

.authorName {
  display: inline-flex !important;
  align-items: center;
  padding: 1.2vw 2vw 1.2vw 0.6vw;
  font-family: 'Inter', sans-serif;
  font-size: var(--sender-height);
  font-weight: 600;
  line-height: 1;
  white-space: nowrap;
  box-sizing: content-box;
  border-radius: 20%;
}
/* remove colon after authors name */
.authorName::after { content: '' !important; }

/*the message payload */
.text {
  display: block !important;
  width: auto;
  background: var(--message-bg) !important;
  border: 2px solid rgba(255, 255, 255, 0.07);
  border-radius: var(--message-radius);
  padding: 1.5vw 1.5vw;
  font-family: 'DM Sans', sans-serif;
  font-size: var(--message-fontsize);
  font-weight: 400;
  color: #eeeef8 !important;
  line-height: 1.5;
  text-align: left;
}

.imageContent {
  height: 4.5vw;
  vertical-align: middle;
  margin: 0 0.3vw;
}
```
</details>
<details>
<summary> Chat Style (Left Aligned, 30 second fade-out)</summary>

```
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=DM+Sans:opsz,wght@9..40,300;9..40,400&display=swap');

:root {
  --sender-bg: rgba(177, 162, 202, 0.85);
  --sender-radius: 4vw 4vw 4vw 4vw;
  --sender-height: 6vw;
  --message-bg: rgba(37, 58, 35, 0.85);
  --message-radius: 0 4vw 4vw 4vw;
  --message-fontsize: 6vw;
}

body {
  background: transparent;
  overflow: hidden;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  padding: 2vw;
  box-sizing: border-box;
  margin: 0;
}

#root > span > img[src='./images/tick.svg'],
#root > span > img[src='./images/error-alt-svgrepo-com.svg'],
#root .ant-spin.ant-spin-spinning,
#root .anticon.anticon-loading.anticon-spin {
  display: none;
}

.messagesListView {
  display: flex;
  flex-direction: column;
  gap: 2vw;
  width: 100%;
}

.message {
  display: flex !important;
  flex-direction: column;
  align-items: flex-start;
  background: transparent !important;
  border: none !important;
  padding: 0 !important;
  width: 100%;
  gap: 0.5vw;
  animation: spotIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) both,
             fadeOut 2s 30s forwards;
}

@keyframes spotIn {
  from { opacity: 0; transform: scale(0.9) translateY(14px); }
  to   { opacity: 1; transform: scale(1)   translateY(0px); }
}

@keyframes fadeOut {
  0%   { opacity: 1; max-height: 500px; }
  70%  { opacity: 0; max-height: 500px; }
  100% { opacity: 0; max-height: 0; overflow: hidden; }
}

.author {
  display: inline-flex !important;
  align-items: center;
  height: var(--sender-height);
  padding: 1.2vw 0.6vw 1.2vw 1.8vw;
  background: var(--sender-bg) !important;
  border-radius: var(--sender-radius);
  box-sizing: border-box;
  max-width: 100%;
  overflow: hidden;
}

/* author sub-items */
.badgeServiceIcon,
.avatar,
.badgeLeft,
.badgeRight {
  display: inline-flex !important;
  align-items: center;
  height: var(--sender-height);
  width: auto;
  box-sizing: content-box;
  border-radius: 20%;
}

.avatar {
  object-fit: cover;
  overflow: hidden;
}

.badgeLeft,
.badgeRight {
  gap: 0.5vw;
}

.badgeLeft .imageContent,
.badgeRight .imageContent {
  height: var(--sender-height) !important;
  width: auto;
}

.authorName {
  display: inline-flex !important;
  align-items: center;
  padding: 1.2vw 2vw 1.2vw 0.6vw;
  font-family: 'Inter', sans-serif;
  font-size: var(--sender-height);
  font-weight: 600;
  line-height: 1;
  white-space: nowrap;
  box-sizing: border-box;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
}
/* remove colon after authors name */
.authorName::after { content: '' !important; }

/*the message payload */
.text {
  display: block !important;
  max-width: 100%;
  box-sizing: border-box;
  background: var(--message-bg) !important;
  border: 2px solid rgba(255, 255, 255, 0.07);
  border-radius: var(--message-radius);
  padding: 1.5vw 1.5vw;
  font-family: 'DM Sans', sans-serif;
  font-size: var(--message-fontsize);
  font-weight: 400;
  color: #eeeef8 !important;
  line-height: 1.5;
  text-align: left;
  overflow-wrap: break-word;
}

.imageContent {
  height: 4.5vw;
  vertical-align: middle;
  margin: 0 0.3vw;
}
```

</details>
