### DISCUSSION TITLE
Fonts in widget is very small. How can I make it bigger?

### DISCUSSION THREAD

**Discussion by eyeofal** [3dproger/AxelChat#738] [General]
Fonts in widget is very small. How can I make it bigger? 
I was trying by myself made it in custom CSS but failed. Is there way easier?

**Comment by 3dproger** [comment]
Hi! Starting with version 0.40.0 I have increased the font in widgets. If you need to increase it even more, try changing the zoom.
If you want to change this using CSS, here are some examples:

For the messages and selected messages widgets:
```CSS
* {
	font-size: 32pt;
}
```

For the counter widget:
```CSS
.bigText {
	font-size: 80pt;
}
```
